"""init

Revision ID: 8c3b2b73dc4d
Revises: 
Create Date: 2023-12-24 03:18:46.862615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c3b2b73dc4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('attribute_id'),
    sa.UniqueConstraint('name'),
    schema='product_management'
    )
    op.create_table('categories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name'),
    schema='product_management'
    )
    op.create_table('category_attributes',
    sa.Column('category_attribute_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['product_management.attributes.attribute_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['product_management.categories.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_attribute_id', 'category_id', 'attribute_id'),
    schema='product_management'
    )
    op.create_table('products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_management.categories.category_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    schema='product_management'
    )
    op.create_table('product_attribute_values',
    sa.Column('product_attribute_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['product_management.attributes.attribute_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product_management.products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_attribute_id', 'product_id', 'attribute_id'),
    schema='product_management'
    )
    op.create_table('product_images',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('image_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product_management.products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id'),
    schema='product_management'
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_management.products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id'),
    schema='product_management'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews', schema='product_management')
    op.drop_table('product_images', schema='product_management')
    op.drop_table('product_attribute_values', schema='product_management')
    op.drop_table('products', schema='product_management')
    op.drop_table('category_attributes', schema='product_management')
    op.drop_table('categories', schema='product_management')
    op.drop_table('attributes', schema='product_management')
    # ### end Alembic commands ###
