"""init

Revision ID: 2afccf5427e3
Revises: 
Create Date: 2023-12-24 03:19:32.129217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2afccf5427e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cart_id'),
    schema='shopping_cart'
    )
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('shipping_address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('order_id'),
    schema='shopping_cart'
    )
    op.create_table('cart_item',
    sa.Column('cart_item_id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['shopping_cart.cart.cart_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_item_id'),
    schema='shopping_cart'
    )
    op.create_table('order_details',
    sa.Column('order_details_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['shopping_cart.orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_details_id'),
    schema='shopping_cart'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details', schema='shopping_cart')
    op.drop_table('cart_item', schema='shopping_cart')
    op.drop_table('orders', schema='shopping_cart')
    op.drop_table('cart', schema='shopping_cart')
    # ### end Alembic commands ###
