apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.service.type: LoadBalancer
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.service.type: LoadBalancer
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/online-electronic-store-online-electronic-store-network: "true"
        io.kompose.service: api-gateway
    spec:
      containers:
        - args:
            - bash
            - -c
            - python app/main.py
          env:
            - name: IS_LOCAL
              value: "false"
          image: agiev/online_electronic_store-api-gateway
          name: api-gateway
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "500m"   # Запрашиваем 0.5 ядра CPU
              memory: "128Mi" # Запрашиваем 256 мебибайт памяти
            limits:
              cpu: "1000m"       # Лимит в 1 ядро CPU
              memory: "256Mi" # Лимит в 512 мебибайт памяти
          volumeMounts:
            - mountPath: /api_gateway_service/log
              name: api-gateway-claim0
      restartPolicy: Always
      volumes:
        - name: api-gateway-claim0
          persistentVolumeClaim:
            claimName: api-gateway-claim0
status: { }
